
BITMAP* getRandomEnemy();
fixed enemy_angle(int z);
fixed mouse_angle();
float deg2Rad(int deg);
int gameOver();
int getRanNum(int min,int max);
int init();
int isInside(int x,int y,int left,int top,int right,int bottom);
int rad2Deg(float rad);
int soundInit();
void bitmapErrorCheck();
void bitmapInit();
void checkMouse();
void collision();
void drawMarine();
void drawVehicle();
void generatePowerup(int index);
void HUD();
void initializeEnemies();
void initTimer();
void input();
void intro();
void loadSounds();
void mappyLoad();
void playIntroduction();
void playRandomDeath();
void playRandomEnemyCall();
void playRandomMarineCall();
void soundErrorCheck();
void startBansheeExplosion(int index);
void startBullet();
void startBulletExplosion(int index);
void startEnemyVehicleBullet(int h);
void startGauss();
void startGaussExplosion(int index);
void startLaser();
void startRocket();
void startRocketExplosion(int index);
void timerCheck();
void updateBackground();
void updateBullets();
void updateEnemies();
void updateExplosions();
void updatePowerups();
void updateReticule();



/*
fixed mouse_angle();
int init();
void bitmapInit();
int soundInit();
void input();
void HUD();
void drawVehicle();
void mappyLoad();
void updateBackground();
void updateReticule();
int isInside(int x,int y,int left,int top,int right,int bottom);
void startBullet();
void startBulletExplosion(int index);
void startRocket();
void startRocketExplosion(int index);
void startGauss();
void startGaussExplosion(int index);
void startLaser();
void updateBullets();
void updateExplosions();
void checkMouse();
void initializeEnemies();
void updateEnemies();
void collision();
int getRanNum(int min,int max);
void loadSounds();
BITMAP* getRandomEnemy();
void playRandomDeath();
void playRandomMarineCall();
void playRandomEnemyCall();
void playIntroduction();
void initTimer();
void timerCheck();
float deg2Rad(int deg);
int rad2Deg(float rad);
void generatePowerup(int index);
void updatePowerups();
void soundErrorCheck();
void startBansheeExplosion(int index);
void startEnemyVehicleBullet(int h);
void intro();
int gameOver();
void bitmapErrorCheck();
*/
